### ISSUE TITLE
Error with Regex String

### ISSUE THREAD

**Issue by petey284** [HotKeyIt/Yaml#1]
Ran into some trouble trying to run Yaml.ahk. I think the problem is with the regex string here:

~~~~
Line 26: 
&&(RegExMatch(A_LoopField,"^(---)?\s*?(-\s)?(`".+`"\s*:\s|'.+'\s*:\s|[^:`"'\{\[]+\s*:\s)")
~~~~

![image](https://user-images.githubusercontent.com/10350886/32618930-1ac999a0-c547-11e7-9ff4-147c273cf760.png)

Am I missing a dependency? Is this based on Autothokey_H?

Error message here:
![image](https://user-images.githubusercontent.com/10350886/32618748-8fe15440-c546-11e7-9acb-20d1e7cd5d6b.png)

**Comment by HotKeyIt** [comment]
Looks like you picked up v2 version and trying to run on v1, use v1 version: https://github.com/HotKeyIt/Yaml/tree/master

**Comment by petey284** [comment]
That was it. I pulled down the master branch and it works. Thanks very much.
