### ISSUE TITLE
Can You update script for v2.138?

### ISSUE THREAD

**Issue by krasnovpro** [HotKeyIt/Yaml#11]
it is very difficult for me to update the obfuscated version of the script myself.

**Comment by krasnovpro** [comment]
It seems better to try an alternative library.

**Comment by HotKeyIt** [comment]
I will update once I have merged v2.138 to AutoHotkey_H (ahkdll).

**Comment by krasnovpro** [comment]
Thank you for your reply. Then I prefer to use JXON.ahk.

**Comment by HotKeyIt** [comment]
Updated for v2.beta

**Comment by krasnovpro** [comment]
How about making the code human-readable?
