### ISSUE TITLE
Functions cannot contain functions

### ISSUE THREAD

**Issue by bagelbits** [HotKeyIt/Yaml#13]
I'm not sure if I'm using your script right however, when I try to include it, I get an error:
```
Error at line 173 in #include file "%A_ScriptDir%\lib\Yaml.ahk"

Line Text: Load(txt,Y:=0)
Error: Functions cannot contain functions.
```

I'm running beta.10 of v2.

**Comment by popstas** [comment]
Hello, @bagelbits, did you solve it?

**Comment by bagelbits** [comment]
I assume so, but I don't remember how.
