### ISSUE TITLE
Compile error n at offset n: character value in \x{...} sequence is too large

### ISSUE THREAD

**Issue by A-User-agh** [HotKeyIt/Yaml#2]
Hi there,

It seems the [line 415](https://github.com/HotKeyIt/Yaml/blob/master/Yaml.ahk#L415) has an issue, especially the part `m)[\x{7F}-\x{7FFFFFFF}]` I'm using AutoHotkey v1.1.26.00`.

This code throws the error, `Compile error 34 at offset 19: character value in \x{...} sequence is too large`
```autohotkey
try {
    s := "a"
    _match := RegExMatch(s,"m)[\x{7F}-\x{7FFFFFFF}]")
} catch e {
    msgbox % e.message "`n"
    exitapp
}
msgbox % _match
```

I encountered the error while using your library for my scripts that use try-catch blocks. `Yaml_Dump()` is used inside a try block and got this error. 

I noticed that in your v2 version, you don't use `\x{7FFFFFFF}` but `\x{7FFF}`.  And if I modify the line like so, the error does not occur. Is it the correct way to fix this?

**Comment by HotKeyIt** [comment]
Yes, I will include that in next release.
