### ISSUE TITLE
[Suggestion] Empty Entry Handling

### ISSUE THREAD

**Issue by A-User-agh** [HotKeyIt/Yaml#3]
Hello,

Currently an empty entry item is treated as an object. I'm wondering if you can consider a change that it becomes an empty string. In my opinion, it is more intuitive and eliminates the check of `IsObject()`.

For example, consider a situation that a program uses a yaml setting file that the user can edit. The user wants to give no value to an option so he/she lets the option blank. The program expects the option value to be a string but the library gives an object. This causes a problem and the program needs to check if the value is not an object. This situation happens also when a program wants to provide a initial settings with a blank value. 

`settings.yaml`
```yaml 
credential:
  first_name: foo
  last_name:
```

```autohotkey
oSettings := yaml( A_ScriptDir "\settings.yaml"  )
msgbox % "is empty: " ( oSettings.credential.last_name ? false : true ) "`n"
    . "is object: " isObject( oSettings.credential.last_name )
```

This gives 
```
is empty: 0
is object: 1
```
Instead, it would be nice to see 
```
is empty: 1
is object: 0
```

**Comment by HotKeyIt** [comment]
New Yaml vor v2 uses empty string instead of object.
