### ISSUE TITLE
Parsing of JSON is incorrect

### ISSUE THREAD

**Issue by kczx3** [HotKeyIt/Yaml#4]
Consider the following valid JSON.

```json
[
    {
      "content": "select * from albums", 
      "id": 1, 
      "title": "one"
    },
    {
      "content": "select substr(name, 2, 4) from tracks", 
      "id": 2, 
      "title": "two"
    }
]
```

Then use the below AHK on this file:
```autohotkey
#Include <Yaml>

obj := Yaml("file.json")

MsgBox(Yaml(obj, -5))
```

The output is the following:
```
[
  {
    "content": select * from albums, 
    "id": 1, 
    "title": one
  }, 
  {
    "content": "select substr(name, 2, 4) from tracks", 
    "id": 2, 
    "title": two
  }
]
```

Strings are not always being quoted.  Also, if your JSON simply contains an empty Array and you load it with Yaml, the returned array will have a length of 1, when it should be 0.

**Comment by HotKeyIt** [comment]
That has been fixed now.
For empty array can you give an example?

**Comment by kczx3** [comment]
> That has been fixed now.
> For empty array can you give an example?

It should be as simple as passing “[]” to the Yaml function

**Comment by HotKeyIt** [comment]
``
Y:=Yaml("[]"), MsgBox Yaml(Y) ; result is [] 
``

**Comment by kczx3** [comment]
> `Y:=Yaml("[]"), MsgBox Yaml(Y) ; result is [] `

That's not the problem.  This is:

`Y:=Yaml("[]"), MsgBox(Y.Length) ; result is 1, should be 0`

**Comment by HotKeyIt** [comment]
That has been fixed now: https://github.com/HotKeyIt/Yaml/commit/bdf22e432f91ff8f508d2ddbeeec421419093e30
