### ISSUE TITLE
Unwanted alphabetizing

### ISSUE THREAD

**Issue by God-damnit-all** [HotKeyIt/Yaml#5]
This alphabetizes everything you import as it creates the arrays... could you make it _not_ do that? The order of entries in my configuration is very important.

**Comment by HotKeyIt** [comment]
Use AutoHotkey_H and replace all Map() calls in Yaml.ahk with [UMap()](http://hotkeyit.github.io/v2/docs/commands/ObjectExtended.htm#UMap) [= unsorted Map].
