### ISSUE TITLE
Broken in AHK 2.0-a122

### ISSUE THREAD

**Issue by mark-wiemer** [HotKeyIt/Yaml#7]
When compiling with the most recent alpha release (2.0-a122), I had to fix a few broken references to `VarSetCapacity`, and I replaced usage of `&var` with `StrPtr(var)`.

However, I am still getting some warnings about variables not being set:

Warning: This variable has not been assigned a value.
     Specifically: local NQ
     Specifically: local P

This is really unfortunate, as a good YAML (or even JSON) parser would be great for AHKv2

**Comment by HotKeyIt** [comment]
I am currently merging v2.0-a122 and will fix the compiler too, should not take too long ;)

**Comment by HotKeyIt** [comment]
Yaml has been updated for v2.122
