### ISSUE TITLE
Error Call to nonexistent function UMap()

### ISSUE THREAD

**Issue by krasnovpro** [HotKeyIt/Yaml#8]
subj

**Comment by krasnovpro** [comment]
I [read the forum](https://www.autohotkey.com/boards/viewtopic.php?p=319517#p319517). Changed `UMap` to `Map`. It's working.

**Comment by HotKeyIt** [comment]
You will need AutoHotey_H v2 for UMap:  https://github.com/HotKeyIt/ahkdll-v2-release
